### ISSUE TITLE
Container consul-template was using 1004852Ki, which exceeds its request of 0.

### ISSUE THREAD

**Issue by imvishalvyas** [hashicorp/consul-template#1278]
I have deployed vault on kubernetes for secret management for my deployments. Now my deployments are include vault init container, Consul-template container and third one is my app container. i am using multiple deployments in my cluster using consul-template. I am using it since last 2 months, But from last 2 days. My all the pods getting evicted and restarted due to consul template using high resource of memory. 

I am getting below error when i search the pod logs.

```
The node was low on resource: memory.  Container consul-template was using 1004852Ki, which exceeds its request of 0.
```

I am using 4G ram and 4 core CPU on my kubernetes GCP. 

### Consul Template version

I am using docker image of  consul-template 'hashicorp/consul-template:alpine'

### Configuration
I have used consul container along with my app and init container of vault. below is my consul container specs.
```
      containers:
        # The consul-template container will pull secrets from Vault and expose
        # them as files on disk.
      - name: consul-template
        image: hashicorp/consul-template:alpine
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
        volumeMounts:
        - name: vault-token
          mountPath: /home/vault
        - name: config
          mountPath: /etc/consul-template
        - name: shared-data
          mountPath: /etc/secrets
        - name: vault-tls
          mountPath: /etc/vault/tls
        env:
        - name: HOME
          value: /home/vault
        - name: VAULT_ADDR
          value: https://myvaultip:8200
        - name: VAULT_CACERT
          value: /etc/vault/tls/ca.pem
        args:
          [
            "-config=/etc/consul-template/consul-template-config.hcl",
            #"-log-level=debug",
          ]
```

My pods getting evicted and restarted 2 or 3 times in a day.
