### ISSUE TITLE
Generating template in docker for nginx

### ISSUE THREAD

**Issue by sweetodev** [hashicorp/consul-template#1301]
I went through this article and was able to get to this point with the help from the author. Article: https://danielparker.me/nginx/consul-template/consul/nginx-consul-template/

The issue is consul-template is not hot reloading the configuration and if I restart the container, it reads but returns erroneous information. 

I've added -s reload flag but it's not taking any effect. 

### Dockerfile
````
FROM hashicorp/consul-template:alpine as template

FROM nginx
COPY --from=template /bin/consul-template /bin/consul-template

WORKDIR /service
COPY nginx.ctmpl nginx.ctmpl
COPY entrypoint.sh entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]

CMD nginx -c /etc/nginx/nginx.conf -g 'daemon off;'
```

### entrypoint.sh

```shell
#!/bin/bash -x
echo "starting entry script"

consul-template -template "nginx.ctmpl:nginx.conf -s reload" -consul-addr "consul:8500" -log-level debug

exec "$@"
```

### nginx.ctmpl

```
upstream department { {{range service "department" }}
    server {{.Address}}:{{.Port}};{{end}}
}

server {
    listen 80 default_server;

    location /departments {
        proxy_pass http://department
    }
}
```

### docker-compose

```
version: '3'

services:

  consul:
    image: consul:1.6.1
    container_name: consul
    ports:
      - 8300:8300
      - 8400:8400
      - 8500:8500

  service:
    container_name: nginx
    build:
      context: service
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - consul
#      - employee
#      - role
      - department
```
