### ISSUE TITLE
Support export of latest public key from the Vault Transit Engine

### ISSUE THREAD

**Issue by chinnaxs** [hashicorp/consul-template#1871]
# Which problem is this feature request solving?

We use Vault [Transit Secret Engine](https://developer.hashicorp.com/vault/api-docs/secret/transit) to generate asymmetric keys. We would like to inject the current/latest generated public key into a k8s Pod. The injection happens via [Vault Agent Sidecar Injector](https://developer.hashicorp.com/vault/docs/platform/k8s/injector) and annotation based Consul-template injection.

# Describe the solution you'd like

We would like to have a new template function `transit <PATH>` where PATH is a path to a Transit Secret Engine, which points to the latest key. e.g. : `transit/export/public-key/fookey/latest`

Then we could inject the secret like this:
```yaml
apiVersion: ...
kind: ...
spec:
  annotation:
    vault.hashicorp.com/agent-inject-secret-signing_key: |
      {{ with transit "transit/export/public-key/signing_key/latest" }}
        {{ .Data.key }}
      {{ end }}

```

# Can you submit a pull request?

No.
