### ISSUE TITLE
with secret "a/b/c/kv/cert" | indent 14 ERROR] agent.template.server: template server error: error="(dynamic): execute: template: :10:81: executing \"\" at <14>: invalid value; expected string"

### ISSUE THREAD

**Issue by patpatpat123** [hashicorp/consul-template#2029]
Hello team,

This is my first issue in this repo.

If not anything else, just wanted to say thanks for all the hard work.

Just wanted to reach out with an issue with the template:

What I am trying to do:

I am trying to combine the with secret construct, with the indent construct

https://github.com/hashicorp/consul-template/blob/main/docs/templating-language.md#indent

https://github.com/hashicorp/consul-template/blob/main/docs/templating-language.md#secret

Background:

```
vault kv get -field=cert -mount=path/to/kv cert
```

would yield:

```
-----BEGIN CERTIFICATE-----
MIIIejCCBmKgAwIBAgITHwABidhlrwxTyZMzlQAFAAGJ2DANBgkqhkiG9w0BAQsF
ADBEMRMwEQYKCZImiZPyLGQBGRYDY29tMRYwFAYKCZImiZPyLGQBGRYGbnZpZGlh
[...]
COsXwzNuSV9fViHbG4ou806yN5ePdnV3Z9fVD+/IXEQLNTsaG+WWS6ThJNUqvtu0
HrmoOOInM7rZWlsmhWIKHjcZ1RHnlayo7tLRw/HuM+2ZlRAf4uLBR52YdGBYDukh
Sd4wRnobbk5zJSLbTVs=
-----END CERTIFICATE-----
```

This is the template I am writing:

```
          spring:
            application:
              name: question
            ssl:
              bundle:
                pem:
                  mycoolclient:
                    keystore:
                      certificate: |
          {{- with secret "path/to/kv/cert" | indent "14" }}
          {{ .Data.data.cert }}
          {{- end }}
```

I am expecting to see

```
          spring:
            application:
              name: question
            ssl:
              bundle:
                pem:
                  mycoolclient:
                    keystore:
                      certificate: |
                         -----BEGIN CERTIFICATE-----
                         MIIIejCCBmKgAwIBAgITHwABidhlrwxTyZMzlQAFAAGJ2DANBgkqhkiG9w0BAQsF
                         ADBEMRMwEQYKCZImiZPyLGQBGRYDY29tMRYwFAYKCZImiZPyLGQBGRYGbnZpZGlh
                         [...]
                         COsXwzNuSV9fViHbG4ou806yN5ePdnV3Z9fVD+/IXEQLNTsaG+WWS6ThJNUqvtu0
                         HrmoOOInM7rZWlsmhWIKHjcZ1RHnlayo7tLRw/HuM+2ZlRAf4uLBR52YdGBYDukh
                         Sd4wRnobbk5zJSLbTVs=
                         -----END CERTIFICATE-----
```

But instead, I am getting this error

```
2025-03-14T08:58:46.199Z [INFO] (runner) starting
2025-03-14T08:58:46.200Z [ERROR] agent.template.server: template server error: error="(dynamic): execute: template: :10:81: executing \"\" at <14>: invalid value; expected string"
2025-03-14T08:58:46.200Z [INFO] (runner) stopping
2025-03-14T08:58:46.200Z [INFO]  agent.template.server: template server stopped
2025-03-14T08:58:46.200Z [INFO]  agent.auth.handler: shutdown triggered, stopping lifetime watcher
2025-03-14T08:58:46.200Z [INFO]  agent.auth.handler: auth retry duration expires in 14m59.688830576s
2025-03-14T08:58:46.200Z [INFO]  agent.auth.handler: auth handler stopped
2025-03-14T08:58:46.200Z [ERROR] agent: runtime error encountered: error="template server: (dynamic): execute: template: :10:81: executing \"\" at <14>: invalid value; expected string"
Error encountered during run, refer to logs for more details.

```

Could you please help?

Thank you for your time

**Comment by patpatpat123** [comment]
P.S:

Just wanted to say that if I am using this template:

```
          spring:
            application:
              name: question
            ssl:
              bundle:
                pem:
                  mycoolclient:
                    keystore:
                      certificate: |
          {{- with secret "path/to/kv/cert" }}
          {{ .Data.data.cert }}
          {{- end }}
```

This would unfortunately yield:

```
spring:
  application:
    name: question
  ssl:
    bundle:
      pem:
        mycoolclient:
          keystore:
            certificate: |
              -----BEGIN CERTIFICATE-----
MIIIejCCBmKgAwIBAgITHwABidhlrwxTyZMzlQAFAAGJ2DANBgkqhkiG9w0BAQsF
ADBEMRMwEQYKCZImiZPyLGQBGRYDY29tMRYwFAYKCZImiZPyLGQBGRYGbnZpZGlh
[...]
COsXwzNuSV9fViHbG4ou806yN5ePdnV3Z9fVD+/IXEQLNTsaG+WWS6ThJNUqvtu0
HrmoOOInM7rZWlsmhWIKHjcZ1RHnlayo7tLRw/HuM+2ZlRAf4uLBR52YdGBYDukh
Sd4wRnobbk5zJSLbTVs=
-----END CERTIFICATE-----
```
