### ISSUE TITLE
liveness probes for k8s?

### ISSUE THREAD

**Issue by mixMugz** [hashicorp/consul-template#2069]
How i can configure liveness probes for consul-template?

**Comment by vanohaker** [comment]
How about this solution?
I'm running consul-template with the -pid-file=/var/run/consul-template.pid flag.
And I use these readinessProbe/livenessProbe settings
```yaml
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - kill -0 $(cat /var/run/consul-template.pid) || exit 1
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: consul-template
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - kill -0 $(cat /var/run/consul-template.pid) || exit 1
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
```
