### ISSUE TITLE
Can't create yaml templates from deeper directories of kv

### ISSUE THREAD

**Issue by onnimonni** [hashicorp/consul-template#258]
Hey!

This might be possible but I couldn't find anything from documentation or source code. I tried to use ```func byKey``` in inner loops but without success.

**What I would like to achieve:**
Generate >=4 levels deep yaml from consul KV.

For example how to turn
**KEY** = **VALUE**
- domains/example.com/container = 12345
- domains/example.com/ssl/key = example.com.key
- domains/example.com/ssl/crt = example.com.crt
- domains/another.com/container = 123456

**to yaml:**
```yaml
domains:
  example.com:
    container: 12345
    ssl:
      key: example.com.key
      crt: example.com.crt
  another.xyz:
    container: 123456
```

**What I tried to do:**
```go
{{range $key, $pairs := tree "domains" | byKey}}{{$key}}:
{{range $pair := $pairs}}  {{.Key}}:{{.Value}}
{{end}}{{end}}
```

**What I get instead:**
```yaml
domains:
  example.com:
    container: 12345
      ssl/key: example.com.key # <============= Should be ssl: key: without '/'
      ssl/crt: example.com.crt # <============= Should be ssl: crt: without '/'
  another.xyz:
    container: 123456
```
