### ISSUE TITLE
Prefixes (like envconsul)

### ISSUE THREAD

**Issue by jonathanmorley** [hashicorp/consul-template#274]
Can we get the -prefix option semantics from envconsul, such that we can specify multiple and the namespaces get merged.

**Comment by sethvargo** [comment]
Hi @jonathanmorley 

Thank you for opening an issue. I'm not sure how that would work? Would you mind providing an example of what you think the API is?

**Comment by c4milo** [comment]
@sethvargo I can see how having a prefix could be useful. Please consider the following example: 

### salt-master-noprefix.ctmpl
```
auto_accept: {{key "q/stg/salt/master/auto_accept"}}

file_roots:
  base:
    - {{key "q/stg/salt/master/file_roots/base"}}

fileserver_backend:
  - {{key "q/stg/salt/master/backend"}}

gitfs_remotes:
  - {{key "q/stg/salt/master/backends/git/remote"}}

gitfs_user: {{key "q/stg/salt/master/backends/git/user"}}
gitfs_password: {{key "q/stg/salt/master/backends/git/password"}}
gitfs_root: {{key "q/stg/salt/master/backends/git/root"}}
gitfs_base: {{key "q/stg/salt/master/backends/git/base"}}
gitfs_provider: {{key "q/stg/salt/master/backends/git/provider"}}
```

Notice how there is a common prefix in all the keys: `q/stg/salt/master`. Perhaps having a prefix option in the template configuration will make this less verbose. Something like: 

```
template {
        prefix = "q/stg/salt/master"
	source = "/etc/consul.d/template/templates/salt-master.ctmpl"
	destination = "/etc/salt/master"
	command = "stop salt-master; start salt-master"
}
```

Which would give us this template: 

### salt-master-prefixed.ctmpl
```yaml
auto_accept: {{key "/auto_accept"}}

file_roots:
  base:
    - {{key "/file_roots/base"}}

fileserver_backend:
  - {{key "/backend"}}

gitfs_remotes:
  - {{key "/backends/git/remote"}}

gitfs_user: {{key "/backends/git/user"}}
gitfs_password: {{key "/backends/git/password"}}
gitfs_root: {{key "/backends/git/root"}}
gitfs_base: {{key "/backends/git/base"}}
gitfs_provider: {{key "/backends/git/provider"}}
```

Is that what you were referring to @jonathanmorley?
