### ISSUE TITLE
The IP address resolved is wrong

### ISSUE THREAD

**Issue by devotox** [hashicorp/consul-template#549]
The IP address that keeps going into my templates are the ip address of registrator and not the container itself which means nginx routes to the wrong place ...

**Comment by slackpad** [comment]
Hi @devotox the problem is likely with your registrator configuration. If you run it with `-internal` it will use the container's IP, not the machine's IP - see http://gliderlabs.com/registrator/latest/user/run/.

**Comment by devotox** [comment]
My registrator is using `-internal` here is the compose file

```
  registrator:
        network_mode: host
        container_name: doctify-registrator
        image: gliderlabs/registrator
        command: -internal consul://consul:8500
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        depends_on:
            - consul
        env_file:
            - ./shared/dev.env
    consul:
        container_name: doctify-consul
        command: agent -data-dir /data -server -bootstrap -protocol 3
        build:
            context: consul
            dockerfile: consul-dockerfile
        #volumes:
        #    - consul_data:/data
        ports:
            - "53:53"
            - "8300:8300"
            - "8301:8301"
            - "8302:8302"
            - "8400:8400"
            - "8500:8500"
            - "8600:8600"
        env_file:
            - ./shared/dev.env
    consul-template:
        network_mode: host
        container_name: doctify-consul-template
        command: -dry -consul consul:8500 -template "/etc/nginx/templates/upstream_servers.ctmpl:/etc/nginx/conf.d/upstream_servers.conf"
        build:
            context: consul
            dockerfile: consul-template-dockerfile
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        volumes_from:
            - server
        depends_on:
            - consul
            - registrator
        env_file:
            - ./shared/dev.env
```

I just get this error

```
~/D/platform >> docker-compose up --force-recreate registrator
Recreating doctify-consul
Recreating doctify-registrator
Attaching to doctify-registrator
doctify-registrator | 2016/02/21 21:20:09 Starting registrator v6 ...
doctify-registrator | 2016/02/21 21:20:10 consul: Get http://consul:8500/v1/status/leader: dial tcp: lookup consul: no such host
doctify-registrator exited with code 1
~/D/platform >>
```
