### ISSUE TITLE
consul template creating the wrong database server

### ISSUE THREAD

**Issue by devotox** [hashicorp/consul-template#578]
my streams ctmpl

```
upstream database_server {
	hash $remote_addr consistent;
	{{range service "database"}}server {{.Address}}:{{.Port}} max_fails=5 fail_timeout=30s weight=1;
	{{else}}server 127.0.0.1:65535;{{end}}
}
```

my docker-compose necessary parts

```

    database:
        build:
            context: ../database
            dockerfile: Dockerfile
        volumes:
            - database_data:/var/lib/postgresql
            - ../shared:/var/app/current/shared
            - /var/log/postgresql
        ports:
            - 5432
        extends:
            service: base
            file: ../shared/base.yml
    server:
        build:
            context: ../nginx
            dockerfile: Dockerfile
        volumes:
            - ../security:/var/app/current/security
            - ../sslcert:/var/app/current/sslcert
            - ../shared:/var/app/current/shared
            - ../nginx:/etc/nginx
            - /var/log/nginx
            - tmp:/tmp
        volumes_from:
            - api
            - website
            - database
        ports:
            - 80:80
            - 443:443
            - 5432:5432
            - 38100:38100
            - 39100:39100
        extends:
            service: base
            file: ../shared/base.yml
```

consul template creates

```
upstream database_server {
        hash $remote_addr consistent;
        server 192.168.99.100:32770 max_fails=5 fail_timeout=30s weight=1;
        server 192.168.99.100:5432 max_fails=5 fail_timeout=30s weight=1;

}
```

This seems to create an entry for both the actual database and the reverse proxy from nginx.

It works for the regular server endpoints like the api but seems to be an issue with the database. I cannot work out what i could possibly be doing wrong.
