### ISSUE TITLE
Trigger only if state changes from fail to passing

### ISSUE THREAD

**Issue by rokka-n** [hashicorp/consul-template#929]
Is it possible to run template only if change in catalog was from fail to passing? 
In other words, I don't want to run template if there is a failing healthcheck in service catalog for something that was healthy.

This is for cassandra cluster, if that makes sense.

```
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "{{range $index, $service := service "${cluster_name}-seed-${env}|passing"}} {{if ne $index 0}},{{end}}{{.Address}}{{end}}"
```
